; platformio.ini

[platformio]
src_dir = firmware/src
include_dir = firmware/include
extra_configs = platformio_override.ini

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/sparkfun/SparkFun_Serial_Controlled_Motor_Driver_Arduino_Library.git

build_flags =
    -I .